In [1]:
# Import libraries and packages
from sklearn.datasets import load_boston
import numpy as np

In [2]:
# Load Boston House Price Data
X, y = load_boston(return_X_y=True)

In [3]:
print(f' Predictors: {X}')

 Predictors: [[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [4]:
print('Outcome: {}' .format(y))

Outcome: [24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50

In [5]:
print(X.shape)
print(X)

print(y.shape)
print(y)

(506, 13)
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
(506,)
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 1

In [6]:
import xgboost as xgb
print(xgb.__version__)

0.90


In [7]:
# Split Train, Test data sets for modeling

from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)


In [11]:
print('Data shape:')
print('X_train: %s, X_test: %s \n' %(X_train.shape, X_test.shape))

Data shape:
X_train: (404, 13), X_test: (102, 13) 



In [14]:
# Train a XGBoost Regression Model
bt = xgb.XGBRegressor(
    max_depth=5, learning_rate=0.2, n_estimators=10, objective="reg:squarederror"
)  # Setup xgboost model

In [15]:
bt.fit(X_train, y_train, verbose=False)  # Train it to our data

XGBRegressor(learning_rate=0.2, max_depth=5, n_estimators=10,
             objective='reg:squarederror')

In [16]:
print(X_test)

[[3.76800e-02 8.00000e+01 1.52000e+00 ... 1.26000e+01 3.92200e+02
  6.62000e+00]
 [4.41780e-01 0.00000e+00 6.20000e+00 ... 1.74000e+01 3.80340e+02
  3.76000e+00]
 [4.52700e-02 0.00000e+00 1.19300e+01 ... 2.10000e+01 3.96900e+02
  9.08000e+00]
 ...
 [4.89822e+00 0.00000e+00 1.81000e+01 ... 2.02000e+01 3.75520e+02
  3.26000e+00]
 [2.90900e-01 0.00000e+00 2.18900e+01 ... 2.12000e+01 3.88080e+02
  2.41600e+01]
 [7.36711e+00 0.00000e+00 1.81000e+01 ... 2.02000e+01 9.67300e+01
  2.15200e+01]]


In [17]:
print(y_test)

[34.6 31.5 20.6 14.5 16.2 22.3 22.8 24.4 19.8 16.7 23.2 15.1 21.  18.9
 48.5 24.1 22.5 16.1 30.3 50.  33.8 10.4 20.4 14.2 10.5 12.7 24.5 16.7
 20.1 17.1 18.4 24.3 50.  23.8 30.7 33.4 15.  10.9 19.1 21.  22.9 22.4
 19.  19.3 27.  27.1 19.1 15.4 19.1 13.5 20.9 19.3 20.5 26.2 12.  19.7
 29.6 34.9  8.3 21.2 14.5 27.5 19.4 32.7 21.1 28.1 17.4 30.1 21.4 20.9
 10.9 21.7  8.8 15.2 26.6  8.7 24.7 38.7  6.3 22.6 43.8 50.  14.5 11.7
 12.5 13.6 21.5 19.1  9.5 17.2 29.8 22.6 21.6 22.2 27.1 17.  22.  50.
  7.2 50.  14.  11. ]


In [18]:
# Predict and compare with real labels
bt.predict(X_test)

array([28.420425 , 24.104414 , 18.68788  , 17.74451  , 18.820585 ,
       19.21481  , 19.65615  , 20.103672 , 18.347971 , 13.479828 ,
       21.405418 , 13.951506 , 18.576729 , 15.482925 , 40.79955  ,
       21.539558 , 21.209105 , 18.272734 , 28.420425 , 41.54057  ,
       29.387716 , 12.817959 , 15.030296 , 14.255787 ,  8.811793 ,
       12.72245  , 23.80478  , 15.62414  , 14.53158  , 18.337036 ,
       16.249468 , 19.131887 , 36.260803 , 21.287066 , 21.448822 ,
       31.270588 , 20.414644 ,  7.859764 , 14.664952 , 19.137093 ,
       19.111242 , 19.745125 , 12.72245  , 17.871775 , 21.221647 ,
       22.97256  , 16.626312 , 12.852083 , 14.112955 , 12.434301 ,
       17.364508 , 18.347971 , 20.706226 , 23.630758 , 11.135802 ,
       15.953214 , 30.14362  , 30.84462  ,  8.347788 , 18.293465 ,
       12.39502  , 12.426752 , 14.871506 , 25.3622   , 18.250927 ,
       20.706226 , 14.837429 , 27.938736 , 16.945335 , 19.137093 ,
       11.0012865, 15.279943 ,  8.015396 , 14.331842 , 26.7281

In [19]:
# Save the model as a file using joblib dump

model_file_name = "DEMO-local-xgboost-reg-model"

In [20]:
# Use joblib which is considered better than pickling 
import joblib
joblib.dump(bt, model_file_name) 

['DEMO-local-xgboost-reg-model']

In [21]:
# Try loading the saved model and test it to make sure everything is fine for deployment

import numpy as np

point_X = X_test[0:5]

print(point_X)

[[3.76800e-02 8.00000e+01 1.52000e+00 0.00000e+00 4.04000e-01 7.27400e+00
  3.83000e+01 7.30900e+00 2.00000e+00 3.29000e+02 1.26000e+01 3.92200e+02
  6.62000e+00]
 [4.41780e-01 0.00000e+00 6.20000e+00 0.00000e+00 5.04000e-01 6.55200e+00
  2.14000e+01 3.37510e+00 8.00000e+00 3.07000e+02 1.74000e+01 3.80340e+02
  3.76000e+00]
 [4.52700e-02 0.00000e+00 1.19300e+01 0.00000e+00 5.73000e-01 6.12000e+00
  7.67000e+01 2.28750e+00 1.00000e+00 2.73000e+02 2.10000e+01 3.96900e+02
  9.08000e+00]
 [1.35472e+00 0.00000e+00 8.14000e+00 0.00000e+00 5.38000e-01 6.07200e+00
  1.00000e+02 4.17500e+00 4.00000e+00 3.07000e+02 2.10000e+01 3.76730e+02
  1.30400e+01]
 [2.53560e-01 0.00000e+00 9.90000e+00 0.00000e+00 5.44000e-01 5.70500e+00
  7.77000e+01 3.94500e+00 4.00000e+00 3.04000e+02 1.84000e+01 3.96420e+02
  1.15000e+01]]


In [22]:
np.savetxt("test_point_regression_sample.csv", point_X, delimiter=",")

In [ ]:
file_name = (
    "test_point_regression_sample.csv"  # customize to your test file
)

In [ ]:
with open(file_name, "r") as f:
    mypayload = np.loadtxt(f, delimiter=",")

In [ ]:
print(mypayload)

In [ ]:
bt1 = joblib.load(model_file_name)

In [ ]:
bt1.predict(mypayload)