In [1]:
# Import libraries and packages
from sklearn import datasets
import numpy as np

In [2]:
# Load Iris Data
iris = datasets.load_iris()

In [3]:
# Split dataset into features and target variable
X = iris.data  
y = iris.target

In [4]:
print(X.shape), print(y.shape)
print(X), print(y)

(150, 4)
(150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1

(None, None)

In [5]:
import xgboost as xgb
print(xgb.__version__)

0.90


In [6]:
# Split Train, Test data sets for modeling
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100, stratify=y)

In [7]:
print(X_train.shape)

(120, 4)


In [8]:
# Train a XGBoost Classifier Model
bt = xgb.XGBClassifier(
    max_depth=5, learning_rate=0.2, n_estimators=10, objective="multi:softmax"
)  # Setup xgboost model

In [9]:
bt.fit(X_train, y_train, verbose=False)  # Train it to our data

XGBClassifier(learning_rate=0.2, max_depth=5, n_estimators=10,
              objective='multi:softprob')

In [10]:
# Predict and compare with real labels
bt.predict(X_test)

array([1, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 2, 2, 0, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 0, 1, 0, 0, 1, 2, 1])

In [11]:
print(y_test)

[1 1 2 2 0 2 1 0 1 1 1 2 2 0 2 0 0 1 0 2 0 1 1 0 2 0 0 2 2 1]


In [12]:
def counts(n):
    results = {}
    for i in n:
        if i not in results:
            results[i] = 1
        else:
            results[i] += 1
    return results

In [13]:
counts(y_test)

{1: 10, 2: 10, 0: 10}

In [14]:
counts(bt.predict(X_test))

{1: 13, 2: 7, 0: 10}

In [15]:
# Save the model as a file using joblib dump
model_file_name = "DEMO-local-xgboost-classifier-model"

In [16]:
import joblib
joblib.dump(bt, model_file_name)

['DEMO-local-xgboost-classifier-model']

In [17]:
# Try loading the saved model and test it to make sure everything is fine for deployment
point_X = X_test[0:5]

print(point_X)

[[5.4 3.  4.5 1.5]
 [5.6 3.  4.1 1.3]
 [6.3 2.8 5.1 1.5]
 [6.  3.  4.8 1.8]
 [5.1 3.3 1.7 0.5]]


In [18]:
np.savetxt("test_point_classifier_sample.csv", point_X, delimiter=",")

In [19]:
file_name = (
    "test_point_classifier_sample.csv"  # customize to your test file
)

In [20]:
with open(file_name, "r") as f:
    mypayload = np.loadtxt(f, delimiter=",")

print(mypayload)

[[5.4 3.  4.5 1.5]
 [5.6 3.  4.1 1.3]
 [6.3 2.8 5.1 1.5]
 [6.  3.  4.8 1.8]
 [5.1 3.3 1.7 0.5]]


In [21]:
bt1 = joblib.load(model_file_name)

In [22]:
bt1.predict(mypayload)

array([1, 1, 1, 2, 0])